### ISSUE TITLE
MIP results bleeding into cancer cases?

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/MIP#1395]
There are two snpEff files in cancer prod directory. There are for this case: primeibex

/home/proj/production/cancer/cases/snpEff_genes.txt
/home/proj/production/cancer/cases/snpEff_summary.html

Balsamic doesn't have snpEff and that case above is not cancer sample. Are setting correctly set for MIP? I noticed these files while cleaning up old files in cancer prod

**Comment by hassanfa** [comment]
There is also /home/proj/production/cancer/cases/vcfparser.log which is for the same case above: primeibex

**Comment by henrikstranneheim** [comment]
It is probably a remnant from starting a MIP process from that directory. 
SNPeff then creates this file based on that later on. Same is true for the vcfparser log.

However, since MIP 8, we do not run snpeff anymore so this is not a problem.  Just delete the snpeff files and they should not reoccur.
For vcfparser the log has been redirected to the analysis folder since a long time ago, so same thing here just delete it.
