### ISSUE TITLE
GT call does not match what I see in IGV

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/MIP#1469]
F0031404
Position 20:44520261
GT call does not match what I see in IGV!? The child and father are both heterozygous, but GT says 1/1 for the child and 0/0 for the father... 

Position 14:88852277
GT call does not match with IGV. The variant does not exist? Position 14:88852280 is homozygous for all three individuals in the family. 

What's the problem? Is there something I miss?

**Comment by henrikstranneheim** [comment]
I think it is hard to say what has happened between bcftools and gatk and the combining of the two. Looks like bcftools is getting it wrong (definitely on the GT call) and this would be a false positive with the GATK variant calling the GT correctly upstream. I do not think it is a combination issue. Since, bcftools is turned off in the current MIP version I would do as Daniel suggests: rerun or just ignore the bcftool call (or if you are really keen - Sanger seq it).

**Comment by henrikstranneheim** [comment]
Closing this one as bcftools is deprecated.
