### ISSUE TITLE
Investigate correlation between GATK GQ and Deepvariant

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#1787]

**Comment by henrikstranneheim** [comment]
Skip Sanger criteria:
- Have a genotype quality (GQ) score equal to GATK’s maximum value of 99
- Called with a “pass” by GATK
- At least 20 reads
- Not be present in segmental duplication regions

**Comment by jemten** [comment]
This is kind of done right?
@ramprasadn, could you add relevant plots to this issue?

**Comment by henrikstranneheim** [comment]
Done

**Comment by ramprasadn** [comment]
`
![gt_quals_causative_variants](https://user-images.githubusercontent.com/20065894/112968389-89c71600-914c-11eb-903c-e011878d4595.jpg)
`

A scatterplot showing the relationship between genotype quality scores from GATK and DeepVariant. On the right and top margins of the scatterplot, we have represented the GQ quality scores from DeepVariant and GATK, respectively, (binwidth is 10 for both plots) as histograms.

Summary: 
An earlier attempt to compare the genotype quality scores from both GATK and DV has shown that the scores generated by the former showed a poor correlation to the empirical scores estimated from a truth set ([Check Fig1 in this article](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa1081/6064144)). The poor correlation, indicative of a lack of biological relevance in GATK’s quality scores is a serious cause of concern. For instance, GQ score is one of the metrics used when physicians decide whether to validate a variant with Sanger sequencing or not. Currently the GQ cutoff is set to 99 or higher, but since that number does not hold much meaning it is possible that we miss to validate variants of poor quality  since we associate high confidence with those calls. However, the authors of the same study reported that the genotype quality scores from DV were found to be more similar to the empirical scores, which will enable the physicians to meaningfully and confidently interpret variant calls.
