### ISSUE TITLE
defining TEST_REFERENCES

### ISSUE THREAD

**Issue by nitzankol** [Clinical-Genomics/MIP#1997]
**Describe the bug**
I get an error message 
[FATAL] 2022/07/07 06:04:07 MIP_ANALYSE - Could not find intended vcfanno_config file: TEST_REFERENCES!/grch38_loqusdb_snv_indel_-2020-03-24-.vcf.gz
the file exists in the reference directory
I can't find TEST_REFERENCES in my config.yaml

**To Reproduce**
change the reference dir

**Expected behavior**
can you add a clear documentation where can I define TEST_REFERENCES or change it to point to the reference?

**Software version (please complete the following information):**
 - MIP: [e.g. 6.0.12]
 - 

**Additional context**

**Comment by jemten** [comment]
Hi @nitzankol,
Missed thesis issue while I was on vacation. 
Need a little bit more background. 
Could you give the command you were trying to run when you got this error?

**Comment by nitzankol** [comment]
Hi Anders,
Thank you very much for your help.
I was running a test analysis -
command:
 ~/MIP/mip analyse rd_dna test_MIP --config grch38_mip_rd_dna_config.yaml
--pedigree_file mip_pedigree.yaml --cluster_constant_path=~/workspace/
--exome_target_bed target.pdd20_hg38.bed=Father,Mother,Proband
--infile_dirs ~/workspace/test_MIP=Father,Mother,Proband
where I've changed reference in grch38_mip_rd_dna_config.yaml to point to
/root/MIP/t/data/references/
otherwise it's the same as the original file
and I got
FATAL] 2022/07/07 06:04:07 MIP_ANALYSE - Could not find intended
vcfanno_config file:
TEST_REFERENCES!/grch38_loqusdb_snv_indel_-2020-03-24-.vcf.gz

I can't find where to define TEST_REFERENCES.
What am I doing wrong?
Thank you very much
Nitzan

‫בתאריך יום ג׳, 9 באוג׳ 2022 ב-17:28 מאת ‪Anders Jemt‬‏ <‪
***@***.***‬‏>:‬

**Comment by jemten** [comment]
OK, the files in the `t` folder is for running the unit tests and integration testing. You will need to download the correct reference files. But first did you manage to install MIP using the supplied install scripts? 

If MIP isn installed and you have slurm on your HPC you can have MIP download refernces by running `mip download -c templates/mip_download_rd_dna_config_-1.0-.yaml --container_config <path to the contianer config if you installed with singularity>  --reference_genome_versions grch38 ----reference_dir <path to where you want to download references> --environment_name <conda environtment name used in installation>`

As you probably see by now it is an involved process to set up MIP. So we are currently in the process of rewriting the pipeline in nextflow to make it easier for others to use. You can check it out [here](https://github.com/nf-core/raredisease). I can try to guide you through the process to set up MIP provided you have a compatible cluster with slurm, conda and singularity or docker. Otherwise I would recommend you to wait a little bit for the nextflow pipeline to be released

cheers,
Anders

**Comment by nitzankol** [comment]
Hi Anders,
thanks for your help.
I've installed MIP using conda and singularity.
I'm not sure we have SLURM - is it mandatory?
I installed MIP using singularity as explained in you GIT page.
the command you gave seems to run but I don't know what you mean by
container_config-
where can I find it?
Thanks
Nitzan

‫בתאריך יום ד׳, 17 באוג׳ 2022 ב-18:15 מאת ‪Anders Jemt‬‏ <‪
***@***.***‬‏>:‬

**Comment by nitzankol** [comment]
Hi Andres,
the tests all run normally.
However when I ran your command I get An ERROR:
get [FATAL] 2022/08/21 06:44:05 MIP_INSTALL - 'singularity exec --bind
/root/MIP/Reference/ensembl-tools-release-unknown/cache:/root/MIP/Reference/ensembl-tools-release-unknown/cache
docker://docker.io/ensemblorg/ensembl-vep:release_104.3 INSTALL.pl --AUTO
cfp --NO_UPDATE --PLUGINS dbNSFP,ExACpLI,LoFtool,MaxEntScan,SpliceAI
--CACHEDIR /root/MIP/Reference/ensembl-tools-release-unknown/cache
--SPECIES homo_sapiens_merged --ASSEMBLY GRCh37' exited with value 255

Anyway we don't have SLURM. reading through the documentation again it
still seems optional rather than mandatory.
maybe you can put a note stating so in the prerequisite part?
should I wait for the nextflow version then?
Thank you
Nitzan


‫בתאריך יום ה׳, 18 באוג׳ 2022 ב-17:57 מאת ‪Anders Jemt‬‏ <‪
***@***.***‬‏>:‬

**Comment by jemten** [comment]
Hi Nitzan
I agree, that should have been more clearly stated. Our goal is to have the first versin of the nextflow pipeline out in October. If you have the time I would recommend you to wait since that should be a more smooth experience than trying to get MIP to work on a non SLURM HPC. 
cheers,
Anders

**Comment by jemten** [comment]
Closing this for now @nitzankol 
Feel free to re-open the issue if needed

**Comment by nitzankol** [comment]
Thanks!
