### ISSUE TITLE
Not called mtDNA variants

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/MIP#2015]
I noticed in case 23013 that a couple of variants in mtDNA are not called by Deepvariant. It is variant m.12775G>A (heteroplasmic) and m.16482A>G (homoplasmic). 

I guess m.12775G>A has a heteroplasmic level below the level that Deepvariant calls? It was called by other callers in case 20016, which also may have a slightly higher heteroplasmic level (15%). Would it be possible for you to manually check the VAF% of this variant in 23013?

The other variant m.16482A>G is homoplasmic and has been called by other callers in several cases (ex 20016, 22100, 21300), but I can not find it called in any sample sequenced after january 2022.

We know that Deepvariant miss variants of lower heteroplasmic level, but what could be the reason for not calling the homoplasmic m.16482A>G.

**Comment by jemten** [comment]
Hi @1ctw,
Thanks for bringing it to our attention. As you say Deepvariant have a lower detection limit when it comes to heteroplasmic variants. When we evaluated the tool we found the limit to be around 10%. That the tool isn't able to recall a homoplasmic variant is a bit strange and we'll look into what could have happened. For your information we are also working on a specialised mitochondrial variant calling workflow to increase our sensitivity for MT variants at lower heteroplasmic levels. That is still some time away though. 

I'll see what I can find on the variants that you mentioned and get back to you

**Comment by jemten** [comment]
Right, I ran deepvariant again on the MT for your patient in order to check the raw calls from the tool. 

The heteroplasmic variant gets reported with an allele fraction of 12.3% but is then filtered out as a reference allele. As I mentioned above, this is a known limitation of DV. 

The homoplasmic variant doesn't get reported at all. Here the cause of a no call is that the variant is close to the very "end" of the MT. Deepvariant works in a similar way as to how we would look at a variant in IGV and it does that by creating sliding windows of 221 basepairs, 110 bases to the left of the candidate and 110 bases to the right. If a variant is closer to the end of the chromosome than this it isn't evaluated. That is usually fine for the other chromosomes but is a problem when doing variant calls on the mitochondria. 

As I mentioned earlier we are working on replacing deepvariant for MT variant calling in order to bring back the level of detection for MT variants.

**Comment by 1ctw** [comment]
Thanks Anders for the explanation! Then I don´t have to worry about missing variants with high heteroplasmic/homoplasmic level further away from the end of the view in IGV. 

Also thanks a lot for checking the heteroplasmic level of the other variant. As you say we are aware of the risk of missing variants with low heteroplasmic level with DP. We are looking forward to the new caller for MT variants!
