### ISSUE TITLE
Update ClinVar

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/MIP#233]
From @AnnHam issue in Scout: https://github.com/Clinical-Genomics/scout/issues/651

Why is a pathogenic variant from ClinVar not shown in SCOUT?

https://scout.scilifelab.se/cust002/F0013626-2/286717ce1d61848c0c18380786aa5d87
https://www.ncbi.nlm.nih.gov/clinvar/variation/381575/

//Anna

**Comment by henrikstranneheim** [comment]
Sorry for the late reply!
It is because it does not exists in clinvar dump version 2017-01-04, which this sample was analyzed with. It is present in clinvar dumbs from 2017-05-01, which is in production now. However, we will update to the most recent version of clinvar with the next MIP update. Starting that process soon(ish)
