### ISSUE TITLE
Evaluate LOFTEE VEp plugin

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/MIP#751]
https://github.com/konradjk/loftee/blob/master/README.md

Would not use it for hard filtering, but maybe to carry over a tag that can be displayed in Scout, potentially to be used in ranking model.

Read more in: https://www.biorxiv.org/search/gnomad?page=1

Kind regards,
Bianca

**Comment by jemten** [comment]
Looks interesting! We're gonna look into how this can be implemented in MIP
cheers,
Anders

**Comment by dnil** [comment]
I used it for the original SweGen db, since derived from ExAC. It does help by identifying quite a number of “Low Confidence” cases where seemingly LOF-variants are actually clearly not. To me, flagging potentially NON LoF frameshifts, splices and stops would be of significant use. Good luck getting it talking to modern VEP. ;-)

**Comment by henrikstranneheim** [comment]
Will not do in MIP.
